[build]
  base = "apps/web"
  command = "npm run build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
